version: '3'

services:
  wildfly-node1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OTHER_NODE_HOSTNAME=wildfly-node2
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - wildfly-cluster

  wildfly-node2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OTHER_NODE_HOSTNAME=wildfly-node1
    ports:
      - "8081:8080"
      - "9991:9990"
    networks:
      - wildfly-cluster

networks:
  wildfly-cluster:
    driver: bridge

